modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/WithersChat/ExtendedCrafting-1.20-unofficial/issues"
    modId="extendedcrafting"
    version="${file.jarVersion}"
    displayName="Extended Crafting: Expanded"
    # updateJSONURL="http://myurl.me/"
    # displayURL="https://blakesmods.com/extended-crafting"
    # logoFile="examplemod.png"
    authors="WithersChat, BlakeBr0 (original author)"
    credits="BlakeBr0 (original author), SpitefulFox"
    description='''
    Adds some new ways to craft items, as well as extra crafting items and utilities. Now with even more tables!
    '''

    [[dependencies.extendedcrafting]]
        modId="forge"
        mandatory=true
        versionRange="[47.1.0,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.extendedcrafting]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.20.1]"
        ordering="NONE"
        side="BOTH"
    [[dependencies.extendedcrafting]]
        modId="cucumber"
        mandatory=true
        versionRange="[7.0.4,)"
        ordering="NONE"
        side="BOTH"